export const ProjectsActionTypes = {
    FETCH_PROJECTS_START: 'FETCH_PROJECTS_START',
    FETCH_PROJECTS_SUCCESS: 'FETCH_PROJECTS_SUCCESS',
    FETCH_PROJECTS_FAILURE: 'FETCH_PROJECTS_FAILURE',
    FILTER_PROJECTS: 'FILTER_PROJECTS'
}